### ISSUE TITLE
3-Legged OAuth `redirect_uri` not being returned in post-authorization querystring

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-js#10]
Could there be an issue with the redirect_uri not being properly mounted to the platform.authUrl() return value? I have a single reference to my redirect_uri which is stored in an environment variable, and I assigned the object passed to authUrl() this value:

// My testing code
https://github.com/bdeanindy/ringcentral-demo/blob/master/controllers/RingCentralAuthorize.js#L38

But the response continually was returning with "redirect_uri does not match". So what I did was retro-fit the redirectUri on the authorizationHandler once the end-user has authorized the app and RingCentral redirects (this is where the redirectUri value was always missing).
https://github.com/bdeanindy/ringcentral-demo/blob/master/controllers/RingCentralAuthorize.js#L53

**Comment by grokify** [comment]
You are seeing this because the API adheres to the OAuth 2.0 spec which doesn't require the authorization code authorization response to redirect to the redirect_uri with `redirect_uri` as query parameter, but it does require the `redirect_uri` body parameter to be posted in the access token request.

The way the SDK works is that you can pass in the URL's query parameters which includes the `code` parameter as long as you manually add the `redirectUri` parameter.

You can read this here:

* Authorization Response: https://tools.ietf.org/html/rfc6749#section-4.1.2
* Access Token Request: https://tools.ietf.org/html/rfc6749#section-4.1.3

To make this easier and remove this step, one consideration is to auto-add the redirect URI to the access token request `login` method which could mean storing the redirect URI along with other app properties, e.g. key, secret, etc.

@kirill-konshin What do you think?

**Comment by kirill-konshin** [comment]
Fixed in #39
