### ISSUE TITLE
Why was the bundle removed?

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#44]
![image](https://cloud.githubusercontent.com/assets/733544/18498243/ae512566-7a67-11e6-840c-0ad2569e337b.png)

Some one in my team likes it a lot but now it's gone.

**Comment by kirill-konshin** [comment]
Polyfills and dependencies should be installed and maintained by developers in their own way. For example Bluebird or ES6 Promise polyfill - this choice should not be dictated by bundle.

**Comment by grokify** [comment]
If there's a need to maintain a bundle, perhaps we can have a separate repo / project that is more opinionated.

**Comment by kirill-konshin** [comment]
I don't mind to have a separate repo, but bundle was never recommended as a good practice, only as a jumpstart solution, which must be replaced before app goes production. So I really don't see much value to keep the bundle and I still don't recommend to use it even in the very beginning.

**Comment by grokify** [comment]
Why must the bundle not be used in production?

**Comment by kirill-konshin** [comment]
If any of other dependencies will require promise or fetch polyfills along with SDK bundle (accidentally, somewhere deep in the deps chain) -- the resulting bundle will have duplicates that cannot be removed. If user compiles from sources those duplicates will be merged. React and Webpack authors, for example, insist on compiling from sources instead of using a pre-built version.

The best practice is that end users deal with polyfills. At our end we can provide recommendations, but not bundles, they are totally useless. We used to have them but this is a dead end that brings more problems than benefits.
