### ISSUE TITLE
Remove wrong keys of localStorage when refresh error

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js#74]
when refresh token error occurs, SDK will call `cache.clean()`.
In`'cache.clean()` ([L41](https://github.com/ringcentral/ringcentral-js/blob/master/src/core/Cache.js#L41)), it will remove all keys that match token cache prefix in localStorage.

if developers use same prefix in SDK cache and user cache, it will remove user cache.
If developers have multiple SDK instance with same prefix (such as: rc rc2), it will user rc2 when rc refresh error

**Comment by kirill-konshin** [comment]
This all is by design.

Default prefix includes dash `rc-`, so if you want `rc2` to be a prefix — you have to add dash manually: `rc2-`. SDK does not add anything on its own except the prefix, no delimiters.

User cache created by SDK has to be removed along with SDK auth cache because it may contain sensitive data, so if SDK logs out or when refresh fails — everything has to be cleaned. If cache has to stay then users are welcome to use `localStorage` directly.

**Comment by embbnux** [comment]
I agree to remove cache after refresh error or logout. But it should not remove by prefix. Cache Module can remember all keys that used by SDK, and clean cache by keys.

**Comment by kirill-konshin** [comment]
Nope, that's by design. Everything that is under the prefix should be wiped. That's the purpose of having this prefix, so that cache should not remember any keys.

As I said previously, you can use storage directly if you want to keep something there:

```js
sdk.cache()._externals.localStorage
```

But that's not recommended. I hardly can imagine a use case for that, just set proper prefixes and there will be no issues.

**Comment by kirill-konshin** [comment]
It was a requirement from integration team based on security reasons, it has been introduced about a couple of years ago.
